frequency: 10  
sensor_timeout: 0.2  
two_d_mode: true

odom0: /odom
odom0_config: [true, true, false, false, false, true, false, false, false, false, false, false, false, false, false]
odom0_differential: false
odom0_queue_size: 20  

imu0: /imu
imu0_config: [false, false, false, false, false, false, true, true, false, true, true, false, false, false, false]
imu0_differential: false
imu0_queue_size: 20 
imu0_remove_gravitational_acceleration: true

world_frame: mocap
base_link_frame: base_link
odom_frame: odom
publish_tf: true
